@Library('cicdlibrary')_

pipeline
{
    agent any
    stages
    {
        stage('Contdownload_Master')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("maven")
                }
            }
        }
        stage('ContBuild_Master')
        {
            steps
            {
                script
                {
                    cicd.newBuild()
                }
            }
        }
        stage('ContDeployment_Master')
        {
            steps
            {
                script
                {
                    cicd.newDeploy("DeclarativePipleinewithSharedLibraries","172.31.12.252","testapp")
                }
            }
        }
        stage('ContTesting_Master')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("FunctionalTesting")
                
                    cicd.runSelenium("DeclarativePipleinewithSharedLibraries")
                }
            }
        }
        stage('ContDelivery_Master')
        {
            steps
            {
                script
                {
                    cicd.newDeploy("DeclarativePipleinewithSharedLibraries","172.31.13.158","prodapp")
                }
            }
        }
    }
}
