@Library('cicdlibrary')_

pipeline
{
    agent any
    stages
    {
        stage('Contdownload_Loans')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("maven")
                }
            }
        }
        stage('ContBuild_Loans')
        {
            steps
            {
                script
                {
                    cicd.newBuild()
                }
            }
        }
    }
}
